#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current window to the workspace of the chosen window

import argparse

import common
from feeders import windows as feeder
from i3_actions import send_window_to_win_workspace


PARSER = argparse.ArgumentParser(prog='i3ci_menu_send_win_to_win')
common.add_monitor_param(PARSER)


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    send_window_to_win_workspace(feeder, mon)
