#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Toggle the workspace names on and off
import re

from Xlib import display
import i3

from i3_actions import Action
from categories import cat


def compute_name(dpy, ws):
    wsinfo = i3.filter(name=ws['name'])
    windows = i3.filter(wsinfo[0], nodes=[])
    # this test checks for empty workspace (no window)
    if windows[0]['window'] is not None:
        #                                                window id
        xwin = dpy.create_resource_object('window', windows[0]['window'])
        cls, _ = xwin.get_wm_class()
        return '{0}: {1}'.format(ws['name'], cat.get(cls, cls))
    return ''


if __name__ == '__main__':
    dpy = display.Display()
    workspaces = i3.msg('get_workspaces')
    if workspaces:
        toggle = re.match(u'^.:.*', workspaces[0]['name']) is None
        action = Action()
        for ws in workspaces:
            if toggle:
                noname = ws['name']
                name = compute_name(dpy, ws)
                if name:
                    action.add_action(Action.rename_workspace, (noname, name))
                else:
                    action.add_action(Action.rename_workspace,
                                      (noname, '{0}: empty'.format(noname)))
            else:
                name = ws['name']
                noname = ws['name'][:1]
                action.add_action(Action.rename_workspace, (name, noname))
        action.process()
