#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Clone the focused window (launch the same application)

import argparse

import common
from i3_actions import clone_window


PARSER = argparse.ArgumentParser(prog='clone_window')
common.add_monitor_param(PARSER)
common.add_free_param(PARSER)

if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    clone_window(mon, args.free)
