#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current window to a free workspace on the specified output.

import argparse

import common
from feeders import free_workspaces as feeder
from i3_actions import send_window_to_free_workspace


PARSER = argparse.ArgumentParser(prog='dmenu_send_win_to_free_wks')
common.add_monitor_param(PARSER)

if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    send_window_to_free_workspace(feeder, mon)
