#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Send the current workspace to a monitor
import argparse

import common
from feeders import outputs as feeder
from i3_actions import send_workspace_to_output


PARSER = argparse.ArgumentParser(prog='dmenu_send_wks_to_output')
common.add_monitor_param(PARSER)

if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    send_workspace_to_output(feeder, mon)
