#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Focus the workspace on the specified monitor

import argparse

import common
from i3_actions import focus_workspace


PARSER = argparse.ArgumentParser(prog='focus_wks')
common.add_monitor_param(PARSER, True)


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    focus_workspace(mon)
