#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Focus the nth window in the current workspace (limited to 10 firsts)

import argparse

from i3_actions import focus_nth_window


PARSER = argparse.ArgumentParser(prog='focus_win')
PARSER.add_argument('-n', '--number',
                    required=True,
                    type=int,
                    choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                    help='Window number (limited to [0,9]).')


if __name__ == '__main__':
    args = PARSER.parse_args()
    focus_nth_window(args.number)
