#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Launch an application on the specified monitor.

import argparse

import common
from feeders import dmenu_path as feeder
from i3_actions import launch_app


PARSER = argparse.ArgumentParser(prog='run')
common.add_monitor_param(PARSER)
common.add_free_param(PARSER)
PARSER.add_argument('-a', '--application',
                    required=True,
                    help=('Application to run.'))


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    launch_app(feeder, app=args.application, output=mon, free=args.free)
