#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Launch an application via i3ci_menu on the specified monitor.

import argparse

import common
from feeders import dmenu_path as feeder
from i3_actions import launch_app


PARSER = argparse.ArgumentParser(prog='i3ci_menu_run')
common.add_monitor_param(PARSER)
common.add_free_param(PARSER)


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    launch_app(feeder, output=mon, free=args.free)
