#!/usr/bin/env python 
# -*- mode: python -*-
# author: syl20bnr (2013)
# goal: Go to the selected i3 window

import argparse
from subprocess import Popen

import i3ci-menu
from constants import DMENU_MAX_ROW, DMENU_FONT, DMENU_HEIGHT


PARSER = argparse.ArgumentParser(prog='i3ci-menu_jump_win')
PARSER.add_argument('-m', '--mode',
                    default=None,
                    help='mode name.')


if __name__ == '__main__':
    args = PARSER.parse_args()
    help_ = ['[a] application',
             '[t] terminal',
             '[w] workspace']
    proc = i3ci-menu.call(p="help",
                      lv=False,
                      f=DMENU_FONT,
                      h=DMENU_HEIGHT)
    reply = proc.communicate('\n'.join(help_))[0]
    if reply:
        if '[a]' in reply:
            Popen('i3-msg mode "new application"', shell=True)
        elif '[t]' in reply:
            Popen('i3-msg mode "new terminal"', shell=True)
