#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current window to a the visible workspace on the next output.

import argparse

import common
from feeders import outputs as feeder
from i3_actions import send_window_to_output


PARSER = argparse.ArgumentParser(prog='i3ci_menu_send_win_to_output')
common.add_monitor_param(PARSER)

if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    send_window_to_output(feeder, mon)
