#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Go to the selected i3 window

import argparse

import common
from feeders import windows as feeder
from i3_actions import jump_to_window


PARSER = argparse.ArgumentParser(prog='i3ci_menu_jump_win')
common.add_monitor_param(PARSER)
PARSER.add_argument('-i', '--instance',
                    default=None,
                    help='X window instance name.')


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    jump_to_window(feeder, args.instance, mon)
