#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Bring the chosen window on the current workspace

import argparse

import common
from feeders import windows as feeder
from i3_actions import bring_window


PARSER = argparse.ArgumentParser(prog='i3ci-menu_bring_win')
common.add_monitor_param(PARSER)


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    bring_window(feeder, mon)