#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Send the current workspace to a monitor

from feeders import workspaces as feeder
from i3_actions import send_window_to_workspace


if __name__ == '__main__':
    send_window_to_workspace(feeder)
