#!/usr/bin/env python
# -*- mode: python -*-

# author: syl20bnr (2013)
# goal: Go to the selected i3 workspace

from feeders import workspaces as feeder
from i3_actions import jump_to_workspace

if __name__ == '__main__':
    jump_to_workspace(feeder)
